# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('shortDef', models.TextField()),
                ('fullDef', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
                ('source', models.CharField(choices=[('habr', 'habrahabr.ru'), ('meduza', 'maduza.io'), ('lenta', 'lenta.ru')], default='habr', max_length=50)),
                ('dateAdd', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
