# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
