# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160801_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news'),
        ),
    ]
