# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160802_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shortDef',
        ),
    ]
