# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_extuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ExtUser',
        ),
    ]
